### ISSUE TITLE
dataset_nonmember_key: str missing from mimir/config.py

### ISSUE THREAD

**Issue by johnhalloran321** [iamgroot42/mimir#13]
Hi, 

Just checked out the code, dataset_nonmember_key: str is missing from the definition of class ExperimentConfig(Serializable):
 in mimir/config.py.

Best,
John

**Comment by iamgroot42** [comment]
Hey John,

Thanks for pointing this out! It was present in an earlier version but was removed later on, but not updated in the config. For now can you use `mi.json` ?
