### ISSUE TITLE
Step by step guide/documentation?

### ISSUE THREAD

**Issue by shanefeng123** [iamgroot42/mimir#18]
Hi, 

Thanks for sharing your code. I want to run the attacks you implemented on my own datasets, but I'm not sure where to start. Is there a guide or documentation the describes this?

Best,
Shane

**Comment by iamgroot42** [comment]
Hey @shanefeng123 . Thanks for your interest in our work!
There's unfortunately no documentation or guide on how to do this, but I did push a general direction in the README just now. Basically you'll want to modify `load_cached` in a way that data is loaded from your particular source. We will modify the code in a way that allows easier extension of new datasets. Let me know if you run into any issues!
