### ISSUE TITLE
Types of gradients computed by GradNormAttack

### ISSUE THREAD

**Issue by Framartin** [iamgroot42/mimir#23]
Hello,
Thanks for your valuable work on mimir! 

If I understand correctly, `GradNormAttack` is computing the average (across layers) of the gradient norm wrt. the model weights.

https://github.com/iamgroot42/mimir/blob/6c611099c669a5a6fd504e55178ef98733f8bb6d/mimir/attacks/gradnorm.py#L41

But the docstring indicates that the gradients are computed w.r.t. input tokens.

https://github.com/iamgroot42/mimir/blob/6c611099c669a5a6fd504e55178ef98733f8bb6d/mimir/attacks/gradnorm.py#L18

Since the [original paper](https://arxiv.org/abs/2402.17012) proposes both, I think there are two solutions:

- Simply fixing the docstring and keeping the current implementation
- Or implementing both gradients norms. I guess that computing gradients wrt input tokens would require modifying `Model.get_probabilities()`

The results in Appendix C.1 suggest that in certain settings, one gradient type outperforms the other, while in other settings, the reverse is observed.

What do you think?

**Comment by iamgroot42** [comment]
Fixed the docstring and closing this issue for now. We might add a token-based gradient attack in a future version, but please feel free to submit a PR in the meanwhile if you have a working implementation!
