### ISSUE TITLE
python package version

### ISSUE THREAD

**Issue by JasonH0810** [iamgroot42/mimir#25]
Hi,

I encountered some version conflicts with Python packages while using your code. Could you please provide the versions of the packages used in your environment?

Thanks!

**Comment by JasonH0810** [comment]
For the transformers >=4.40.0, there will be a ValueError: 'olmo' is already used by a Transformers config, pick another name.

Also, for the latest versions of NumPy and pandas, there can also be some package conflicts.

**Comment by iamgroot42** [comment]
Hi @JasonH0810  - I used Python 3.9.7 in my setup, with `torch==2.0.1` and `transformers==4.39.1`, but other people that have used the repository have experimented with different (at least later) versions and seem to be able to run our scripts.

>  there can also be some package conflicts.

Did you face any in particular?
